# Profile for basic configuration on NVIDIA Jetson devices

# Enable/disable toggles for setup steps
RUN_UPDATE_SYSTEM=true          # Updates the system (apt only, use this if you want to update the system and have ROS installed in docker)
RUN_UPDATE_SYSTEM_AND_ROS=false # Updates the system and ROS (use this if you want to update the system and ROS that is installed directly on the host, not in docker)

RUN_INSTALL_BASIC_PACKAGES=true      # Installs basic packages, such as vim, curl, git, etc.
RUN_INSTALL_DOCKER=true              # Installs docker and adds the current user to the docker group
RUN_INSTALL_INTEL_WIFI_DRIVERS=false # Installs iwlwifi drivers for Intel WiFi cards (used for some old NUCs, not needed for Jetson)

RUN_DISABLE_POWER_SAVING=true   # Disables power saving features (such as hibernation) and sets the higher power profile
RUN_GENERATE_SSH_CONFIG=false   # Generates SSH config and hosts file with predefined hostnames and IP addresses
RUN_SET_SWAP_16GB=true          # Set swap size to 16 GB
RUN_CLEANUP_HOME_DIRECTORY=true # Cleans up the home directory by removing directories ~/Downloads, ~/Templates, ~/Pictures, etc. If the directories are not empty, they won't be removed
RUN_SETUP_RTC_ON_JETSON=true    # Configures Jetson devices to use the hardware RTC
RUN_SET_TIMEZONE_TO_PRAGUE=true # Sets the timezone to Europe/Prague

RUN_FIX_NETWORK_INTERFACE_NAMES=true # New versions of Linux use "predictable" network names (such as enp3s0). This option restores reverts back to old eth0, wlan0, etc. names

RUN_SET_WALLPAPER=true            # Sets the wallpaper to $VAL_WALLPAPER_NAME. See subscripts/6Branding/DISREGARD/wallpapers for available wallpapers
VAL_WALLPAPER_NAME="RoboCore.png" # Name of the wallpaper to set. Must be in subscripts/6Branding/DISREGARD/wallpapers
RUN_SET_PROFILE_PICTURE=true      # Sets the profile picture
RUN_SET_TERMINAL_MOTD=true       # Sets the terminal MOTD (message of the day) to a custom message
