# Sample profile

# Enable/disable toggles for setup steps
RUN_UPDATE_SYSTEM=false                 # Updates the system (apt only, use this if you want to update the system and have ROS installed in docker)
RUN_UPDATE_SYSTEM_AND_ROS=false         # Updates the system and ROS (use this if you want to update the system and ROS that is installed directly on the host, not in docker)

RUN_INSTALL_BASIC_PACKAGES=false        # Installs basic packages, such as vim, curl, git, etc.
RUN_INSTALL_DOCKER=false                # Installs docker and adds the current user to the docker group
RUN_INSTALL_INTEL_WIFI_DRIVERS=false    # Installs iwlwifi drivers for Intel WiFi cards (used for NUCs, not needed for Jetson)

RUN_DISABLE_HIBERNATION=false           # Disables hibernation to prevent drone from going to sleep
RUN_GENERATE_SSH_CONFIG=false           # Generates SSH config and hosts file with predefined hostnames and IP addresses
RUN_SET_SWAP_16GB=false                 # Set swap size to 16 GB

RUN_FIX_NETWORK_INTERFACE_NAMES=false   # New versions of Linux use "predictable" network names (such as enp3s0). This option restores reverts back to old eth0, wlan0, etc. names
RUN_CONFIGURE_NETWORKING=true          # Configures Ethernet and WiFi interfaces with information provided lower in this file

# Networking
NETWORKING_DELETE_PREVIOUS_NETPLAN_CONFIGS=true   # Deletes all previous netplan configs
NETWORKING_NETPLAN_CONFIG="network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: yes
      dhcp6: no
      addresses: [
        10.10.20.101/24
      ]
      routes:
        - to: default
          via: 10.10.20.1
          metric: 100
      nameservers:
        addresses: [8.8.8.8]
  wifis:
    wlan0:
      dhcp4: no
      dhcp6: no
      addresses: [
        192.168.112.2/24
      ]
      routes:
        - to: default
          via: 192.168.112.1
          metric: 200
      access-points:
        "f4f_robot":
          password: "mikrokopter"
      nameservers:
        addresses: [8.8.8.8]"